import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getProducts } from "../lib/api";
import Link from 'next/link'
export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         All Products Below
        </h1>
        <div className={styles.grid}>
          {
            products.map(product => (
              <Link href="/[slug]" as={`/${product.slug}`} styles={{ cursor: "pointer" }}>
                <a className={styles.card}>
                  <h2>{product.name}</h2>
                  <p>{product.seo.description}</p>
                  <img src={product.productPhoto.url[0]} height={200} width={300}/>
                </a>

              </Link>
            ))
          }
          {/* {
            products[0].data.productPhoto.url.map(url => <img src={url}></img>)
          } */}
        </div>
      </main>

    </div>
  )
}

export const getStaticProps = async () => {
  const { products } = await getProducts()

  return { props: { products } };
};